"""empty message

Revision ID: e25b83818ee2
Revises: 
Create Date: 2021-10-11 13:12:22.307061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e25b83818ee2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tb_class_plan',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('teacher_code', sa.String(), nullable=True),
    sa.Column('teacher_name', sa.String(), nullable=True),
    sa.Column('group_code', sa.String(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('period', sa.Enum('FIRST', 'SECOND', 'THIRD', 'FOURTH', name='periodenum'), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('contents', sa.Text(), nullable=True),
    sa.Column('evaluation', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_class_plan_goal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('class_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_plan_id'], ['tb_class_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tb_class_plan_material',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('class_plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['class_plan_id'], ['tb_class_plan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tb_class_plan_material')
    op.drop_table('tb_class_plan_goal')
    op.drop_table('tb_class_plan')
    # ### end Alembic commands ###
